#cloud-config

users:
  - name: edward
  - name: minecraft

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

runcmd:
  - apt-get autoremove -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - apt-key fingerprint 0EBFCD88
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install docker-ce -y
  - docker --version
  - docker volume create minecraftbackup
  - mkdir -p /repo/minecraft
  - git clone https://github.com/edwardfward/minecraft.git /repo/minecraft
  - docker build -f /repo/minecraft/minecraft.DockerFile -t rowansworld /repo/minecraft
  - docker run -d -p 9999:9999 -v minecraftbackup:/minecraft/backup --name RowansWorld rowansworld:latest

